main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
    path('signup/', views.signup, name='signup'),
    path('login/', views.login_request, name="login"),
    path("logout/", views.logout_request, name="logout"),

]

storysembilan/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
]

main/models.py
from django.db import models

# Create your models here.

main/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class SignUpForm(UserCreationForm):
    first_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    last_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    email = forms.EmailField(max_length=254, help_text='Required. Inform a valid email address.')

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2', )

class NewUserForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2")

    def save(self, commit=True):
        user = super(NewUserForm, self).save(commit=False)
        user.email = self.cleaned_data["email"]
        if commit:
            user.save()
        return user

main/views.py
from django.contrib.auth import login, authenticate, logout
from django.shortcuts import render, redirect
from main.forms import SignUpForm, NewUserForm
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm

def home(request):
    return render(request, 'main/home.html')

def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            user.is_staff = True
            user.save()
            login(request, user)
            return redirect('main:home')
    else:
        form = SignUpForm()
    return render(request, 'main/signup.html', {'form': form})

def login_request(request):
    if request.method == 'POST':
        form = AuthenticationForm(request=request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('/')
            else:
                messages.error(request, "Invalid username or password.")
        else:
            messages.error(request, "Invalid username or password.")
    form = AuthenticationForm()
    return render(request = request,
                    template_name = "main/login.html",
                    context={"form":form})

def logout_request(request):
    logout(request)
    return redirect("main:home")

main/templates/main/home.html
{% extends 'base.html' %} 
{% load static %}
<!DOCTYPE html>
<html>
          
</html>

main/templates/main/login.html
{% extends 'base.html' %}

{% block content %}

    <div class="container">
        <form method="POST">
        {% csrf_token %}
        {{form.as_p}}
            <button style="background-color:#F4EB16; color:blue" class="btn btn-outline-info" type="submit">Login</button>
        </form>
        Don't have an account? <a href="{% url 'main:signup' %}" target="blank"><strong>register here</strong></a>!
    </div>
{% endblock %}

main/templates/main/signup.html
{% extends 'base.html' %} 
{% load static %}
<!DOCTYPE html>

<html>
<body style="margin-left: 100px">
  {% block content %}
    <h2>Sign up</h2>
    <form method="post">
      {% csrf_token %}
      {% for field in form %}
        <p>
          {{ field.label_tag }}<br>
          {{ field }}
          {% if field.help_text %}
            <small style="color: grey">{{ field.help_text }}</small>
          {% endif %}
          {% for error in field.errors %}
            <p style="color: red">{{ error }}</p>
          {% endfor %}
        </p>
      {% endfor %}
      <button type="submit">Sign up</button>
    </form>
  {% endblock %}
</body>

</html>

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">


<head>
    <link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr"crossorigin="anonymous">
    <link rel='stylesheet' href='https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css'>
	<title>Story 9</title>
</head>
<nav class="navbar fixed-top navbar-expand-lg navbar-light scrolling-navbar">
    <div class="collapse navbar-collapse" id="mainNavBar">
        <ul class="nav navbar-nav">
            <li class="active"><a href="{% url 'main:home' %}">Home</a></li>
        </ul>

        {% if request.user.is_authenticated %}
        <ul class="navbar-nav navbar-right">
            <li style="margin-right:20px"><a href="#"><span class="glyphicon "></span> Hi {{ request.user.first_name }} {{ request.user.last_name }}</a></li>
            <li style="margin-right:100px"><a href="{% url 'main:logout' %}"><span class="glyphicon glyphicon-log-in"></span> Logout</a></li>
            <!--<li style="margin-right:100px"><a href="/admin/logout/?next=/"><span class="glyphicon glyphicon-log-in"></span> Logout</a></li>-->
        </ul>

        {% else %}
        
        <ul class="navbar-nav navbar-right">
            <li style="margin-right:20px"><a href="{% url 'main:signup' %}"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
            <li style="margin-right:100px"><a href="{% url 'main:login' %}"><span class=" glyphicon glyphicon-log-in"></span> Login</a></li>
            <!--<li style="margin-right:100px"><a href="/admin/login/?next=/"><span class=" glyphicon glyphicon-log-in"></span> Login</a></li>-->
        </ul>
    	
        {% endif %}
    </div>
</nav>
{% block content%}

{% endblock content %}
</html>